name: Deploy PHP Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy via rsync over SSH
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avz --delete
        path: ./
        remote_path: /home/weather-bot/htdocs/weather-bot.suyunbek.uz
        remote_host: ${{ secrets.SERVER_IP }}
        remote_user: ${{ secrets.SERVER_USER }}
        remote_key: ${{ secrets.SERVER_SSH_KEY }}
